    var APIS = [
        {
            "datatype":"3",
            "site":"bug-p2pool",
            "title":"蟲礦",
            "stitle":"蟲礦",
            "url":"http://pool.pcbug.idv.tw:9337/static/",
            "type":"LTC"
        },
        {
            "datatype":"3",
            "site":"consortium-p2pool",
            "title":"Consortium Pool",
            "stitle":"Consortium Pool",
            "url":"http://121.12.115.170:22550/static",
	    "apiurl":"http://121.12.115.170:22550/",
            "type":"DOGE"
        },
        {
            "datatype":"1",
            "site":"wemineltc",
            "title":"www.wemineltc.com",
            "stitle":"WML",
            "url":"https://www.wemineltc.com",
            "apiurl":"https://www.wemineltc.com/api?api_key=",
            "type":"LTC"
        },
        {
            "datatype":"1",
            "site":"wemineall",
            "title":"www.wemineall.com",
            "stitle":"WMA",
            "url":"https://www.wemineall.com",
            "apiurl":"https://www.wemineall.com/api?api_key=",
            "type":"BTC"
        },
        {
            "datatype":"1",
            "site":"give-me-coins-ltc",
            "title":"give-me-coins.com",
            "stitle":"GMC",
            "url":"https://give-me-coins.com",
            "type":"LTC"
        },
        {
            "datatype":"4",
            "site":"hashfaster",
            "title":"ltc.hashfaster.com",
            "stitle":"HashFaster",
            "url":"https://ltc.hashfaster.com/index.php",
	    "apiurl":"https://ltc.hashfaster.com/index.php?page=api&api_key=",
            "type":"LTC"
        },
        {
            "datatype":"3",
            "site":"litecoin-tw-p2pool",
            "title":"Litecoin.TW",
            "stitle":"P2Pool.TW",
            "url":"http://litecoin.tw:9327/static/",
            "type":"LTC"
        },
        {
            "datatype":"1",
            "site":"wemineftc",
            "title":"www.wemineftc.com",
            "stitle":"WMF",
            "url":"https://www.wemineftc.com",
            "type":"FTC"
        },
        {
            "datatype":"1",
            "site":"give-me-coins-ftc",
            "title":"give-me-coins.com",
            "stitle":"GMC",
            "url":"https://give-me-coins.com",
            "type":"FTC"
        },
        {
            "datatype":"1",
            "site":"khore",
            "title":"nvc.khore.org",
            "stitle":"KHORE",
            "url":"https://nvc.khore.org",
            "type":"NVC"
        },
        {
            "datatype":"2",
            "site":"btc-guild",
            "title":"www.btcguild.com",
            "stitle":"BTCGuild",
            "url":"https://www.btcguild.com",
            "type":"BTC"
        },
        {
            "datatype":"4",
            "site":"hashfaster-doge",
            "title":"doge.hashfaster.com",
            "stitle":"HashFaster",
            "url":"http://doge.hashfaster.com/",
	    "apiurl":"https://doge.hashfaster.com/index.php?page=api&&api_key=",
            "type":"DOGE"
        },
        {
            "datatype":"4",
            "site":"maxcoin-pool",
            "title":"maxcoinpool.com",
            "stitle":"Maxcoin",
            "url":"http://maxcoinpool.com/",
	    "apiurl":"http://maxcoinpool.com/index.php?page=api&&api_key=",
            "type":"MAX"
        },
        {
            "datatype":"4",
            "site":"max-coin",
            "title":"pool.max-coin.net",
            "stitle":"Max-Coin",
            "url":"https://pool.max-coin.net/",
	    "apiurl":"https://pool.max-coin.net/index.php?page=api&&api_key=",
            "type":"MAX"
        },
        {
            "datatype":"4",
            "site":"hashfaster-max",
            "title":"max.hashfaster.com",
            "stitle":"HashFaster",
            "url":"https://max.hashfaster.com/index.php",
	    "apiurl":"https://max.hashfaster.com/index.php?page=api&api_key=",
            "type":"MAX"
        },
        {
            "datatype":"4",
            "site":"darkcoin-drk",
            "title":"www.drkpool.com",
            "stitle":"DarkCoinPool",
            "url":"https://www.drkpool.com/index.php",
            "apiurl":"http://www.drkpool.com/index.php?page=api&api_key=",
            "type":"DRK"
        }
    ]

